export const LIMITS = {
  MAX_FILE_SIZE_BYTES: 50 * 1024 * 1024, // 50MB
  MAX_TAGS_PER_ENTITY: 10,
  MAX_TAG_LENGTH: 50,
  MAX_CHECKLIST_ITEMS_PER_TASK: 30,
  MAX_CUSTOM_FIELDS_PER_FIRM: 20,
  MAX_CUSTOM_FIELD_OPTIONS: 50,
  MAX_MENTIONS_PER_COMMENT: 10,
  MAX_CONCURRENT_SESSIONS: 5,
  MAX_DOCUMENT_REMINDER_COUNT: 3,
  PRESIGNED_URL_EXPIRY_SECONDS: 900, // 15 minutes
  COMMENT_MAX_LENGTH: 5000,
  TASK_TITLE_MAX_LENGTH: 300,
  TASK_DESCRIPTION_MAX_LENGTH: 10000,
};
