export enum ConstitutionType {
  PROPRIETORSHIP = 'PROPRIETORSHIP',
  PARTNERSHIP = 'PARTNERSHIP',
  COMPANY = 'COMPANY',
  LLP = 'LLP',
  TRUST = 'TRUST',
  SOCIETY = 'SOCIETY',
  OTHER = 'OTHER',
}
