export enum EngagementCategory {
  GST = 'GST',
  INCOME_TAX = 'INCOME_TAX',
  TDS = 'TDS',
  ROC_COMPLIANCE = 'ROC_COMPLIANCE',
  AUDIT = 'AUDIT',
  PAYROLL = 'PAYROLL',
  ADVISORY = 'ADVISORY',
  ACCOUNTING = 'ACCOUNTING',
  OTHER = 'OTHER',
}
