export enum EntityType {
  INDIVIDUAL = 'INDIVIDUAL',
  HUF = 'HUF',
  PARTNERSHIP_FIRM = 'PARTNERSHIP_FIRM',
  LLP = 'LLP',
  PRIVATE_LIMITED = 'PRIVATE_LIMITED',
  PUBLIC_LIMITED = 'PUBLIC_LIMITED',
  TRUST = 'TRUST',
  SOCIETY = 'SOCIETY',
  AOP = 'AOP',
  BOI = 'BOI',
  OTHER = 'OTHER',
}
