export enum TaskStatus {
  TO_DO = 'TO_DO',
  IN_PROGRESS = 'IN_PROGRESS',
  AWAITING_CLIENT = 'AWAITING_CLIENT',
  UNDER_REVIEW = 'UNDER_REVIEW',
  PARTNER_APPROVAL = 'PARTNER_APPROVAL',
  DONE = 'DONE',
  CANCELLED = 'CANCELLED',
}
